name: Update Blogs JSON

on:
  push:
    branches: ["main"]
    paths:
      - 'blogs.php'
  schedule:
    - cron: '10 7-23/3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run news parser
        run: php blogs.php

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/blogs.json
          git commit -m "Auto-update news.json" || echo "No changes"

      - name: Push changes
        run: git push
